### ISSUE TITLE
Service Booking Pages Creation

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#27]
# Service Booking Components
- [x] Booking Selection
- [x] Payment Confirmation
- [x] Order Confirmation

## Desktop Mockup
![Booking Desktop Page Mockup](https://user-images.githubusercontent.com/32943879/63066104-9abf0700-bed6-11e9-804e-013bfbaba812.png)

## Mobile
![Booking Mobile Portrait Mockup](https://user-images.githubusercontent.com/32943879/63066105-9b579d80-bed6-11e9-9281-d1c7a9afbe6b.png)

**Comment by vai1205** [comment]
Service booking page created, lt fetches the data from the database and redirects the user to the payment confirmation page and then to the order confirmation page. 

- [ ] Code for fronend.

- [ ] Link to database.

- [ ] Server side code.

- [ ] Link pages in the correct order and check if the user is logged in to access the payment page and confirmation page.

- [ ] Save the complete client detail, selected fixer detail and order details in Orders collection.

**Comment by vai1205** [comment]
@CodeMeKathy changes done and published live. Please check and close the issue.
