### ISSUE TITLE
Animation Additions

### ISSUE THREAD

**Issue by CodeMeKathy** [chingu-voyages/v10-geckos-team-14#30]
## Animations

- [x] Contact Form Submission Alert.

- [x]  Hover effect on select service tiles.

- [x]  Button Press effect on clicking service tiles on the home page.

- [x]  Selecting fixer from the list on the booking page gives an alert with the details of the selected fixer.

- [x] Show an alert/warning message when the user submits the booking form without selecting any fixer from the list.

- [x] Add hover state on login/logout button.

**Comment by vai1205** [comment]
@CodeMeKathy The animation list is updated. Please review.

**Comment by vai1205** [comment]
@CodeMeKathy The Animations are added in the app. Please check and close the issue.

## Contact Form Submission Alert

![Screen Shot 2019-08-14 at 3 36 45 PM](https://user-images.githubusercontent.com/50205141/63013208-5cf7b980-bea9-11e9-8ea7-fbe8b2437d79.png)

## Hover effect on select service tiles
![service tile hover](https://user-images.githubusercontent.com/50205141/63013582-266e6e80-beaa-11e9-8176-98d1745b2d5e.gif)

## Button Press effect on clicking service tiles on the home page
![button press effect on service tiles](https://user-images.githubusercontent.com/50205141/63013821-c3310c00-beaa-11e9-8459-19669ff78722.gif)

## Fixer selection alert
![fixer selection alert](https://user-images.githubusercontent.com/50205141/63014076-51a58d80-beab-11e9-85b6-a2fb48b0eb01.gif)

## No fixer selected alert
![no fixer alert](https://user-images.githubusercontent.com/50205141/63014220-ae08ad00-beab-11e9-9035-4894e585629b.gif)

## Hover Stage on Login/Logout button
![hover on login](https://user-images.githubusercontent.com/50205141/63014384-0a6bcc80-beac-11e9-9ec2-8458527f4e9b.gif)

**Comment by vai1205** [comment]
@CodeMeKathy Please review and close the issue.
